dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.3
  - safe-global/safe-contracts@1.3.0-libs.0

compiler:
  solc:
    version: 0.8.13
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'
      - '@gnosis.pm=safe-global/safe-contracts@1.3.0-libs.0'