dependencies:
  - uniswap/v2-core@1.0.0
  - uniswap/v2-periphery@1.0.0-beta.0
  - OpenZeppelin/openzeppelin-contracts@4.3.3

compiler:
  solc:
    remappings:
      - '@uniswap/v2-core=uniswap/v2-core@1.0.0'
      - '@uniswap/v2-periphery=uniswap/v2-periphery@1.0.0-beta.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'

networks:
  development:
      cmd_settings:
        default_balance: 1000000